replicaCount: 1
image:
  repository: ironmansoftware/universal
  tag: "5.0.0"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 5000
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: powershell.local
      paths:
        - path: /
          pathType: ImplementationSpecific
resources: {}
env: {}
