apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-psu
  labels:
    app: {{ .Release.Name }}-psu
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-psu
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-psu
    spec:
      containers:
        - name: psu
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          env:
            {{- range $key, $value := .Values.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
